plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

dependencies {
  implementation 'androidx.core:core:1.13.1'
  testImplementation 'junit:junit:4.13.2'
}

group = 'expo.modules.studyfocusmode'
version = '0.1.0'

android {
  namespace "expo.modules.studyfocusmode"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
